import "~/styles/globals.css";

import type { Metadata } from "next";
import { Pacifico } from "next/font/google";
import localFont from "next/font/local";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { TRPCReactProvider } from "~/trpc/react";
import { Toaster } from "sonner";

const headingFont = Pacifico({
  subsets: ["latin", "cyrillic"],
  variable: "--font-heading",
  display: "swap",
  weight: "400",
});

const mainFont = localFont({
  src: "../../public/font.ttf",
  variable: "--font-main",
  display: "swap",
});

export const metadata: Metadata = {
  title: "bite of bliss",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="ru"
      className={`${headingFont.variable} ${mainFont.variable} font-main`}
    >
      <body>
        <TRPCReactProvider>
          <NuqsAdapter>
            {children}
          </NuqsAdapter>
          <Toaster/>
        </TRPCReactProvider>
      </body>
    </html>
  );
}